# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run Test"
  lane :tests do
    scan(
      scheme: 'Tests',
      clean: true,
      code_coverage: true
    )
  end

  desc "Run UI Test"
  lane :ui_tests do
    scan(
      scheme: 'UITests',
      clean: true,
      code_coverage: true
    )
  end

  desc "Run All Test"
  lane :all_tests do
    tests
    ui_tests
  end

  desc "Just Building"
  lane :build do
    ensure_git_status_clean
    gym(configuration: 'Debug')
    reset_git_repo
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "Swift_2048")
    upload_to_testflight
  end
end
